name: Generate Snake Game from GitHub Contributions Grid

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day
  workflow_dispatch:

jobs:
  generate_snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: platane/snk@v2
        with:
          github_user_name: codewithgyan467 # Make sure this is the correct username
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snake animation
        uses: actions/upload-artifact@v3
        with:
          name: github-contribution-grid-snake
          path: .github/contribution-grid-snake.svg
